dist: xenial
language: php

php:
  - 7.1

env:
  matrix:
    - DEPS="high"
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-suggest --prefer-source"
    - XDEBUG="false"

cache:
  directories:
    - ./vendor

before_install:
    # determine INI file
    - export INI_DIR=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d
    - export INI=$INI_DIR/travis.ini
    - if [[ "$TRAVIS_TAG" = '' ]]; then export COMPOSER_ROOT_VERSION=dev-master; fi
    # disable default memory limit
    - echo memory_limit = 2G >> $INI
    - if [[ "$XDEBUG" = 'false' && -f $INI_DIR/xdebug.ini ]]; then phpenv config-rm xdebug.ini; fi
    - composer clear-cache

install:
  - if [[ "$DEPS" = 'high' ]]; then travis_retry composer $DEFAULT_COMPOSER_FLAGS update; fi
  - if [[ "$DEPS" = 'low' ]]; then travis_retry composer $DEFAULT_COMPOSER_FLAGS --prefer-lowest --prefer-stable update; fi

script:
  - vendor/bin/phpunit tests
  - vendor/bin/psalm --with-spirit

# Base test matrix (php/env)
matrix:
  fast_finish: true
